networks:
  traefik_proxy:
    external: true

services:
  valkey:
    image: valkey/valkey:${DB_VERSION}
    restart: always
    container_name: valkey
    command: valkey-server /etc/valkey/valkey.conf
    environment:
      - TZ='Europe/Paris'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s  
    expose:
      - "6379"
    networks:
      - traefik_proxy
# uncomment the labels below to enable the remote access to the valkey server      
#    labels:
#      - traefik.enable=true
#      - traefik.tcp.routers.valkey.rule=HostSNI(`*`)
#      - traefik.tcp.routers.valkey.entrypoints=db-redis
#      - traefik.tcp.routers.valkey.service=valkey-svc
#      - traefik.tcp.services.valkey-svc.loadbalancer.server.port=6379
#      - traefik.tcp.routers.valkey.middlewares=tcpSecureByIp@file
    volumes:
      - ./valkey/data:/data
      - ./valkey/conf/valkey.conf:/etc/valkey/valkey.conf
